= poly-rs

a polymorphic language using Hindley-Milner type inference, based on on sdiehl's https://github.com/sdiehl/write-you-a-haskell/tree/master/chapter7/poly_constraints[poly_constraints] language and his http://dev.stephendiehl.com/fun/006_hindley_milner.html[tutorial].

reimplemented in Rust 🦀 of course.
and featuring LISP syntax for ease of parsing.

== building & running

with https://nixos.org/download.html[`nix` installed]:

----
$ nix-shell

# enter repl
$ cargo run --bin polyi
< repl appears >
< ctrl-d to exit >

# interpret code from a file
$ cargo run --bin poly ./examples/ex1.poly
< output >
----

== optional: building & running with `lorri` and `direnv` (more for developers)

* install https://github.com/target/lorri[lorri]
* install https://github.com/direnv/direnv[direnv] (including shell hook)
* in root directory of project: `direnv allow`

you'll probably need to start `lorri daemon` somewhere, so that builds with be evaluated.

the advantage of this approach is that lorri will constantly rebuild & manage nix dependencies, and will cache them nicely.
`nix-shell` will sometimes leave you in a lurch if e.g. your network goes down and it decides it needs to re-fetch everything.
`lorri`, by comparison, would just allow you to use an old build, and would wait to update the build when network access was restored.
